spring:
  application:
    name: eureka-client


server:
  port: ${PORT:8001}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
