server:
  port: 8003
rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: source
        output:
          destination: processor
