server:
  port: 8003
spring:
  rabbitmq:
    host=localhost
    port=5672
    username=guest
    password=guest
  cloud:
    stream:
      bindings:
        input:
          destination=source
        output:
          destination=processor
